apiVersion: v2
name: filedr-postgresql
description: A Helm chart for deploying PostgreSQL for the filedr service
type: application
version: 0.1.0
appVersion: "16"
dependencies:
  - name: postgresql
    version: 16.6.6
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled