---
apiVersion: v2
name: iceberg-rest-catalog
description: A Helm chart for Kubernetes
type: application
version: 0.1.0

dependencies:
  - name: postgresql
    version: 16.6.6
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: trino
    version: 0.32.0
    repository: https://trinodb.github.io/charts
    condition: trino.enabled