apiVersion: v1
kind: ConfigMap
metadata:
  name: iceberg-rest-catalog
  labels:
    app: iceberg-rest-catalog
    component: data-hub
data:
  application.yml: |
    ---
    # profile: common

    management:
      endpoint:
        health:
          probes:
            enabled: true
      health:
        livenessState:
          enabled: true
        readinessState:
          enabled: true
        db:
          enabled: false
      server:
        port: {{ .Values.service.management.server.port }}

    server:
      port: {{ .Values.service.server.port }}
      servlet:
        context-path: /
      shutdown: graceful


    ---
    # profile: dev
    spring:
      profiles: dev


    ---
    # profile: prod
    spring:
      profiles: prod
