apiVersion: apps/v1
kind: Deployment
metadata:
  name: iceberg-rest-catalog
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: iceberg-rest-catalog
  template:
    metadata:
      labels:
        app: iceberg-rest-catalog
        component: data-hub
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: iceberg-rest
        image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        env:
          - name: AWS_REGION
            value: "{{ .Values.s3.region }}"
          - name: CATALOG_WAREHOUSE
            value: "{{ .Values.catalog.warehouse }}"
          - name: CATALOG_IO__IMPL
            value: "org.apache.iceberg.aws.s3.S3FileIO"
          - name: CATALOG_S3_ENDPOINT
            value: {{ .Values.s3.endpoint }}
          - name: CATALOG_S3_ACCESS__KEY__ID
            value: {{ .Values.s3.accessKey }}
          - name: CATALOG_S3_SECRET__ACCESS__KEY
            value: {{ .Values.s3.secretKey }}
          - name: CATALOG_S3_PATH__STYLE__ACCESS
            value: "True"
          - name: CATALOG_CLIENTS
            value: "1"
          - name: SPRING_PROFILES_ACTIVE
            value: "{{ .Values.service.spring.profiles.active }}"
          - name: CATALOG_CATALOG__IMPL
            value: org.apache.iceberg.jdbc.JdbcCatalog
          - name: CATALOG_URI
            value: "{{ .Values.catalog.jdbc.url }}"
          - name: CATALOG_JDBC_USER
            value: iceber-rest-catalog-user
          - name: CATALOG_JDBC_PASSWORD
            value: password
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
        {{- toYaml $.Values.deployment.resources | nindent 12 }}
        volumeMounts:
          - name: rest-catalog-volume
            mountPath: /opt/rest-catalog/conf/application.yml
            subPath: application.yml
        ports:
          - name: jetty
            containerPort: {{ .Values.service.jetty.server.port }}
            protocol: TCP
        lifecycle:
          preStop:
            exec:
              command: [ "sleep", "15" ]
        livenessProbe:
          httpGet:
            path: /v1/namespaces
            port: 8181
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /v1/namespaces
            port: 8181
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
        - name: rest-catalog-volume
          configMap:
            name: iceberg-rest-catalog
