apiVersion: v1
kind: Service
metadata:
  name: iceberg-rest-catalog
  labels:
    app: iceberg-rest-catalog
    component: data-hub
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.jetty.server.port }}
      targetPort: jetty
      protocol: TCP
      name: jetty
  selector:
    app: iceberg-rest-catalog
